// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.justafewmistakes.nim.common.protobuf;

public final class RequestProtocol {
  private RequestProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求者的id
     * </pre>
     *
     * <code>int64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string requestName = 5;</code>
     */
    java.lang.String getRequestName();
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string requestName = 5;</code>
     */
    com.google.protobuf.ByteString
        getRequestNameBytes();

    /**
     * <pre>
     * 请求体的消息id
     * </pre>
     *
     * <code>int64 requestMsgId = 9;</code>
     */
    long getRequestMsgId();

    /**
     * <pre>
     * 请求体的消息
     * </pre>
     *
     * <code>string requestMsg = 2;</code>
     */
    java.lang.String getRequestMsg();
    /**
     * <pre>
     * 请求体的消息
     * </pre>
     *
     * <code>string requestMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRequestMsgBytes();

    /**
     * <pre>
     * 请求的类型(1：确认连接，2、3:心跳，4：单聊，5：群聊，6：离线消息通知推送（要求收到的服务器发送离线消息到目前的网关））
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    int getType();

    /**
     * <pre>
     *群id用于发送群聊的时候
     * </pre>
     *
     * <code>int64 groupId = 7;</code>
     */
    long getGroupId();

    /**
     * <pre>
     * 目的地（群的id，用户的id，服务器的id等等等等）(负数就不进行扩散，表示仅进行确认或心跳)
     * </pre>
     *
     * <code>int64 destination = 4;</code>
     */
    long getDestination();

    /**
     * <pre>
     * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    java.lang.String getTransit();
    /**
     * <pre>
     * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    com.google.protobuf.ByteString
        getTransitBytes();

    /**
     * <pre>
     *发送的时间
     * </pre>
     *
     * <code>int64 sendTime = 8;</code>
     */
    long getSendTime();
  }
  /**
   * <pre>
   * 目前request和response有一些问题，response行为只在各个服务端产生（网关的服务端+IM服务器的服务端）
   * </pre>
   *
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      requestName_ = "";
      requestMsg_ = "";
      transit_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              requestMsg_ = s;
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 32: {

              destination_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              requestName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              transit_ = s;
              break;
            }
            case 56: {

              groupId_ = input.readInt64();
              break;
            }
            case 64: {

              sendTime_ = input.readInt64();
              break;
            }
            case 72: {

              requestMsgId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.justafewmistakes.nim.common.protobuf.RequestProtocol.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.justafewmistakes.nim.common.protobuf.RequestProtocol.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.class, com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <pre>
     * 请求者的id
     * </pre>
     *
     * <code>int64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int REQUESTNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object requestName_;
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string requestName = 5;</code>
     */
    public java.lang.String getRequestName() {
      java.lang.Object ref = requestName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string requestName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestNameBytes() {
      java.lang.Object ref = requestName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTMSGID_FIELD_NUMBER = 9;
    private long requestMsgId_;
    /**
     * <pre>
     * 请求体的消息id
     * </pre>
     *
     * <code>int64 requestMsgId = 9;</code>
     */
    public long getRequestMsgId() {
      return requestMsgId_;
    }

    public static final int REQUESTMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestMsg_;
    /**
     * <pre>
     * 请求体的消息
     * </pre>
     *
     * <code>string requestMsg = 2;</code>
     */
    public java.lang.String getRequestMsg() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求体的消息
     * </pre>
     *
     * <code>string requestMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMsgBytes() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * 请求的类型(1：确认连接，2、3:心跳，4：单聊，5：群聊，6：离线消息通知推送（要求收到的服务器发送离线消息到目前的网关））
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private long groupId_;
    /**
     * <pre>
     *群id用于发送群聊的时候
     * </pre>
     *
     * <code>int64 groupId = 7;</code>
     */
    public long getGroupId() {
      return groupId_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 4;
    private long destination_;
    /**
     * <pre>
     * 目的地（群的id，用户的id，服务器的id等等等等）(负数就不进行扩散，表示仅进行确认或心跳)
     * </pre>
     *
     * <code>int64 destination = 4;</code>
     */
    public long getDestination() {
      return destination_;
    }

    public static final int TRANSIT_FIELD_NUMBER = 6;
    private volatile java.lang.Object transit_;
    /**
     * <pre>
     * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    public java.lang.String getTransit() {
      java.lang.Object ref = transit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transit_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTransitBytes() {
      java.lang.Object ref = transit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 8;
    private long sendTime_;
    /**
     * <pre>
     *发送的时间
     * </pre>
     *
     * <code>int64 sendTime = 8;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (!getRequestMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestMsg_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (destination_ != 0L) {
        output.writeInt64(4, destination_);
      }
      if (!getRequestNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestName_);
      }
      if (!getTransitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, transit_);
      }
      if (groupId_ != 0L) {
        output.writeInt64(7, groupId_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(8, sendTime_);
      }
      if (requestMsgId_ != 0L) {
        output.writeInt64(9, requestMsgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (!getRequestMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestMsg_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (destination_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, destination_);
      }
      if (!getRequestNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestName_);
      }
      if (!getTransitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, transit_);
      }
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, groupId_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, sendTime_);
      }
      if (requestMsgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, requestMsgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request)) {
        return super.equals(obj);
      }
      com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request other = (com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getRequestName()
          .equals(other.getRequestName())) return false;
      if (getRequestMsgId()
          != other.getRequestMsgId()) return false;
      if (!getRequestMsg()
          .equals(other.getRequestMsg())) return false;
      if (getType()
          != other.getType()) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (getDestination()
          != other.getDestination()) return false;
      if (!getTransit()
          .equals(other.getTransit())) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + REQUESTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRequestName().hashCode();
      hash = (37 * hash) + REQUESTMSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestMsgId());
      hash = (37 * hash) + REQUESTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDestination());
      hash = (37 * hash) + TRANSIT_FIELD_NUMBER;
      hash = (53 * hash) + getTransit().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 目前request和response有一些问题，response行为只在各个服务端产生（网关的服务端+IM服务器的服务端）
     * </pre>
     *
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        com.justafewmistakes.nim.common.protobuf.RequestProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.justafewmistakes.nim.common.protobuf.RequestProtocol.internal_static_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.justafewmistakes.nim.common.protobuf.RequestProtocol.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.class, com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.Builder.class);
      }

      // Construct using com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        requestName_ = "";

        requestMsgId_ = 0L;

        requestMsg_ = "";

        type_ = 0;

        groupId_ = 0L;

        destination_ = 0L;

        transit_ = "";

        sendTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.justafewmistakes.nim.common.protobuf.RequestProtocol.internal_static_Request_descriptor;
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request getDefaultInstanceForType() {
        return com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request build() {
        com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request buildPartial() {
        com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request result = new com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request(this);
        result.requestId_ = requestId_;
        result.requestName_ = requestName_;
        result.requestMsgId_ = requestMsgId_;
        result.requestMsg_ = requestMsg_;
        result.type_ = type_;
        result.groupId_ = groupId_;
        result.destination_ = destination_;
        result.transit_ = transit_;
        result.sendTime_ = sendTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request) {
          return mergeFrom((com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request other) {
        if (other == com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (!other.getRequestName().isEmpty()) {
          requestName_ = other.requestName_;
          onChanged();
        }
        if (other.getRequestMsgId() != 0L) {
          setRequestMsgId(other.getRequestMsgId());
        }
        if (!other.getRequestMsg().isEmpty()) {
          requestMsg_ = other.requestMsg_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.getDestination() != 0L) {
          setDestination(other.getDestination());
        }
        if (!other.getTransit().isEmpty()) {
          transit_ = other.transit_;
          onChanged();
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       * 请求者的id
       * </pre>
       *
       * <code>int64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 请求者的id
       * </pre>
       *
       * <code>int64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求者的id
       * </pre>
       *
       * <code>int64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object requestName_ = "";
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string requestName = 5;</code>
       */
      public java.lang.String getRequestName() {
        java.lang.Object ref = requestName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string requestName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRequestNameBytes() {
        java.lang.Object ref = requestName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string requestName = 5;</code>
       */
      public Builder setRequestName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string requestName = 5;</code>
       */
      public Builder clearRequestName() {
        
        requestName_ = getDefaultInstance().getRequestName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string requestName = 5;</code>
       */
      public Builder setRequestNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestName_ = value;
        onChanged();
        return this;
      }

      private long requestMsgId_ ;
      /**
       * <pre>
       * 请求体的消息id
       * </pre>
       *
       * <code>int64 requestMsgId = 9;</code>
       */
      public long getRequestMsgId() {
        return requestMsgId_;
      }
      /**
       * <pre>
       * 请求体的消息id
       * </pre>
       *
       * <code>int64 requestMsgId = 9;</code>
       */
      public Builder setRequestMsgId(long value) {
        
        requestMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求体的消息id
       * </pre>
       *
       * <code>int64 requestMsgId = 9;</code>
       */
      public Builder clearRequestMsgId() {
        
        requestMsgId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object requestMsg_ = "";
      /**
       * <pre>
       * 请求体的消息
       * </pre>
       *
       * <code>string requestMsg = 2;</code>
       */
      public java.lang.String getRequestMsg() {
        java.lang.Object ref = requestMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求体的消息
       * </pre>
       *
       * <code>string requestMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMsgBytes() {
        java.lang.Object ref = requestMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求体的消息
       * </pre>
       *
       * <code>string requestMsg = 2;</code>
       */
      public Builder setRequestMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求体的消息
       * </pre>
       *
       * <code>string requestMsg = 2;</code>
       */
      public Builder clearRequestMsg() {
        
        requestMsg_ = getDefaultInstance().getRequestMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求体的消息
       * </pre>
       *
       * <code>string requestMsg = 2;</code>
       */
      public Builder setRequestMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMsg_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 请求的类型(1：确认连接，2、3:心跳，4：单聊，5：群聊，6：离线消息通知推送（要求收到的服务器发送离线消息到目前的网关））
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 请求的类型(1：确认连接，2、3:心跳，4：单聊，5：群聊，6：离线消息通知推送（要求收到的服务器发送离线消息到目前的网关））
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的类型(1：确认连接，2、3:心跳，4：单聊，5：群聊，6：离线消息通知推送（要求收到的服务器发送离线消息到目前的网关））
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long groupId_ ;
      /**
       * <pre>
       *群id用于发送群聊的时候
       * </pre>
       *
       * <code>int64 groupId = 7;</code>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <pre>
       *群id用于发送群聊的时候
       * </pre>
       *
       * <code>int64 groupId = 7;</code>
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群id用于发送群聊的时候
       * </pre>
       *
       * <code>int64 groupId = 7;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private long destination_ ;
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）(负数就不进行扩散，表示仅进行确认或心跳)
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public long getDestination() {
        return destination_;
      }
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）(负数就不进行扩散，表示仅进行确认或心跳)
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public Builder setDestination(long value) {
        
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）(负数就不进行扩散，表示仅进行确认或心跳)
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public Builder clearDestination() {
        
        destination_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object transit_ = "";
      /**
       * <pre>
       * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public java.lang.String getTransit() {
        java.lang.Object ref = transit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTransitBytes() {
        java.lang.Object ref = transit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder setTransit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder clearTransit() {
        
        transit_ = getDefaultInstance().getTransit();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于中转，单流/群聊 无需中转的时候为空，用于需要另一个gateway的时候。在客户端请求连接时为自己的ip+port，用于向服务器告知.离线消息时存自己所连的网关，用于发回
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder setTransitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transit_ = value;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *发送的时间
       * </pre>
       *
       * <code>int64 sendTime = 8;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送的时间
       * </pre>
       *
       * <code>int64 sendTime = 8;</code>
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的时间
       * </pre>
       *
       * <code>int64 sendTime = 8;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request();
    }

    public static com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.justafewmistakes.nim.common.protobuf.RequestProtocol.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\"\262\001\n\007Request\022\021\n\trequestId" +
      "\030\001 \001(\003\022\023\n\013requestName\030\005 \001(\t\022\024\n\014requestMs" +
      "gId\030\t \001(\003\022\022\n\nrequestMsg\030\002 \001(\t\022\014\n\004type\030\003 " +
      "\001(\005\022\017\n\007groupId\030\007 \001(\003\022\023\n\013destination\030\004 \001(" +
      "\003\022\017\n\007transit\030\006 \001(\t\022\020\n\010sendTime\030\010 \001(\003B;\n(" +
      "com.justafewmistakes.nim.common.protobuf" +
      "B\017RequestProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "RequestId", "RequestName", "RequestMsgId", "RequestMsg", "Type", "GroupId", "Destination", "Transit", "SendTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
