// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.justafewmistakes.nim.common.protobuf;

public final class ResponseProtocol {
  private ResponseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 回应者的id
     * </pre>
     *
     * <code>int64 responseId = 1;</code>
     */
    long getResponseId();

    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string responseName = 5;</code>
     */
    java.lang.String getResponseName();
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string responseName = 5;</code>
     */
    com.google.protobuf.ByteString
        getResponseNameBytes();

    /**
     * <pre>
     * 回应体的内容
     * </pre>
     *
     * <code>string responseMsg = 2;</code>
     */
    java.lang.String getResponseMsg();
    /**
     * <pre>
     * 回应体的内容
     * </pre>
     *
     * <code>string responseMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMsgBytes();

    /**
     * <pre>
     * 回应的编码
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    int getType();

    /**
     * <pre>
     * 目的地（群的id，用户的id，服务器的id等等等等）
     * </pre>
     *
     * <code>int64 destination = 4;</code>
     */
    long getDestination();

    /**
     * <pre>
     * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    java.lang.String getTransit();
    /**
     * <pre>
     * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    com.google.protobuf.ByteString
        getTransitBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      responseName_ = "";
      responseMsg_ = "";
      transit_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responseId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMsg_ = s;
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 32: {

              destination_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              responseName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              transit_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.class, com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.Builder.class);
    }

    public static final int RESPONSEID_FIELD_NUMBER = 1;
    private long responseId_;
    /**
     * <pre>
     * 回应者的id
     * </pre>
     *
     * <code>int64 responseId = 1;</code>
     */
    public long getResponseId() {
      return responseId_;
    }

    public static final int RESPONSENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object responseName_;
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string responseName = 5;</code>
     */
    public java.lang.String getResponseName() {
      java.lang.Object ref = responseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求者的昵称
     * </pre>
     *
     * <code>string responseName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getResponseNameBytes() {
      java.lang.Object ref = responseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSEMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMsg_;
    /**
     * <pre>
     * 回应体的内容
     * </pre>
     *
     * <code>string responseMsg = 2;</code>
     */
    public java.lang.String getResponseMsg() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 回应体的内容
     * </pre>
     *
     * <code>string responseMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMsgBytes() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * 回应的编码
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 4;
    private long destination_;
    /**
     * <pre>
     * 目的地（群的id，用户的id，服务器的id等等等等）
     * </pre>
     *
     * <code>int64 destination = 4;</code>
     */
    public long getDestination() {
      return destination_;
    }

    public static final int TRANSIT_FIELD_NUMBER = 6;
    private volatile java.lang.Object transit_;
    /**
     * <pre>
     * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    public java.lang.String getTransit() {
      java.lang.Object ref = transit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transit_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
     * </pre>
     *
     * <code>string transit = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTransitBytes() {
      java.lang.Object ref = transit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseId_ != 0L) {
        output.writeInt64(1, responseId_);
      }
      if (!getResponseMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMsg_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (destination_ != 0L) {
        output.writeInt64(4, destination_);
      }
      if (!getResponseNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, responseName_);
      }
      if (!getTransitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, transit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, responseId_);
      }
      if (!getResponseMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMsg_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (destination_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, destination_);
      }
      if (!getResponseNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, responseName_);
      }
      if (!getTransitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, transit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response)) {
        return super.equals(obj);
      }
      com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response other = (com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response) obj;

      if (getResponseId()
          != other.getResponseId()) return false;
      if (!getResponseName()
          .equals(other.getResponseName())) return false;
      if (!getResponseMsg()
          .equals(other.getResponseMsg())) return false;
      if (getType()
          != other.getType()) return false;
      if (getDestination()
          != other.getDestination()) return false;
      if (!getTransit()
          .equals(other.getTransit())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseId());
      hash = (37 * hash) + RESPONSENAME_FIELD_NUMBER;
      hash = (53 * hash) + getResponseName().hashCode();
      hash = (37 * hash) + RESPONSEMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDestination());
      hash = (37 * hash) + TRANSIT_FIELD_NUMBER;
      hash = (53 * hash) + getTransit().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.justafewmistakes.nim.common.protobuf.ResponseProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.class, com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.Builder.class);
      }

      // Construct using com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseId_ = 0L;

        responseName_ = "";

        responseMsg_ = "";

        type_ = 0;

        destination_ = 0L;

        transit_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response getDefaultInstanceForType() {
        return com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response build() {
        com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response buildPartial() {
        com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response result = new com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response(this);
        result.responseId_ = responseId_;
        result.responseName_ = responseName_;
        result.responseMsg_ = responseMsg_;
        result.type_ = type_;
        result.destination_ = destination_;
        result.transit_ = transit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response) {
          return mergeFrom((com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response other) {
        if (other == com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response.getDefaultInstance()) return this;
        if (other.getResponseId() != 0L) {
          setResponseId(other.getResponseId());
        }
        if (!other.getResponseName().isEmpty()) {
          responseName_ = other.responseName_;
          onChanged();
        }
        if (!other.getResponseMsg().isEmpty()) {
          responseMsg_ = other.responseMsg_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getDestination() != 0L) {
          setDestination(other.getDestination());
        }
        if (!other.getTransit().isEmpty()) {
          transit_ = other.transit_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long responseId_ ;
      /**
       * <pre>
       * 回应者的id
       * </pre>
       *
       * <code>int64 responseId = 1;</code>
       */
      public long getResponseId() {
        return responseId_;
      }
      /**
       * <pre>
       * 回应者的id
       * </pre>
       *
       * <code>int64 responseId = 1;</code>
       */
      public Builder setResponseId(long value) {
        
        responseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回应者的id
       * </pre>
       *
       * <code>int64 responseId = 1;</code>
       */
      public Builder clearResponseId() {
        
        responseId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object responseName_ = "";
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string responseName = 5;</code>
       */
      public java.lang.String getResponseName() {
        java.lang.Object ref = responseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string responseName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getResponseNameBytes() {
        java.lang.Object ref = responseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string responseName = 5;</code>
       */
      public Builder setResponseName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string responseName = 5;</code>
       */
      public Builder clearResponseName() {
        
        responseName_ = getDefaultInstance().getResponseName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求者的昵称
       * </pre>
       *
       * <code>string responseName = 5;</code>
       */
      public Builder setResponseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object responseMsg_ = "";
      /**
       * <pre>
       * 回应体的内容
       * </pre>
       *
       * <code>string responseMsg = 2;</code>
       */
      public java.lang.String getResponseMsg() {
        java.lang.Object ref = responseMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 回应体的内容
       * </pre>
       *
       * <code>string responseMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMsgBytes() {
        java.lang.Object ref = responseMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 回应体的内容
       * </pre>
       *
       * <code>string responseMsg = 2;</code>
       */
      public Builder setResponseMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回应体的内容
       * </pre>
       *
       * <code>string responseMsg = 2;</code>
       */
      public Builder clearResponseMsg() {
        
        responseMsg_ = getDefaultInstance().getResponseMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回应体的内容
       * </pre>
       *
       * <code>string responseMsg = 2;</code>
       */
      public Builder setResponseMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMsg_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 回应的编码
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 回应的编码
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回应的编码
       * </pre>
       *
       * <code>int32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long destination_ ;
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public long getDestination() {
        return destination_;
      }
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public Builder setDestination(long value) {
        
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目的地（群的id，用户的id，服务器的id等等等等）
       * </pre>
       *
       * <code>int64 destination = 4;</code>
       */
      public Builder clearDestination() {
        
        destination_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object transit_ = "";
      /**
       * <pre>
       * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public java.lang.String getTransit() {
        java.lang.Object ref = transit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTransitBytes() {
        java.lang.Object ref = transit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder setTransit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder clearTransit() {
        
        transit_ = getDefaultInstance().getTransit();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于中转，无需中转的时候为空，用于需要另一个gateway的时候
       * </pre>
       *
       * <code>string transit = 6;</code>
       */
      public Builder setTransitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transit_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response();
    }

    public static com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.justafewmistakes.nim.common.protobuf.ResponseProtocol.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\"}\n\010Response\022\022\n\nresponse" +
      "Id\030\001 \001(\003\022\024\n\014responseName\030\005 \001(\t\022\023\n\013respon" +
      "seMsg\030\002 \001(\t\022\014\n\004type\030\003 \001(\005\022\023\n\013destination" +
      "\030\004 \001(\003\022\017\n\007transit\030\006 \001(\tB<\n(com.justafewm" +
      "istakes.nim.common.protobufB\020ResponsePro" +
      "tocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "ResponseId", "ResponseName", "ResponseMsg", "Type", "Destination", "Transit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
